plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.beanbeaver.bbreceiptkit"
    compileSdk = 36
    buildToolsVersion = "36.0.0"
    // Pinned here too, not just in :app. This module's own strip task doesn't
    // feed the app (AGP publishes MERGED_NATIVE_LIBS to downstream consumers on
    // purpose, so :app can extract symbols), but leaving it unpinned emits
    // "Unable to strip the following libraries" noise — and an unpinned module
    // is exactly how the two drift apart.
    ndkVersion = providers.gradleProperty("bb.ndkVersion").get()

    defaultConfig {
        minSdk = 34
        consumerProguardFiles("consumer-rules.pro")
        ndk {
            abiFilters += listOf("arm64-v8a")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    sourceSets {
        getByName("main") {
            // UniFFI-generated Kotlin (git-ignored until first ./build-android.sh)
            java.srcDirs("src/main/kotlin")
            jniLibs.srcDirs("src/main/jniLibs")
        }
    }
}

dependencies {
    // UniFFI 0.28 Kotlin bindings use JNA. The Android AAR ships the right
    // native loader pieces; plain jar is not enough on-device. 5.17+ ships a
    // 16 KB-aligned libjnidispatch.so (required by Play for Android 15+ targets).
    api("net.java.dev.jna:jna:5.17.0@aar")
}

/**
 * Refuse to build a release against debug native libraries.
 *
 * v0.4.0 went to Play as an 81.8 MiB bundle because `src/main/jniLibs/` still
 * held the 224 MB output of `PROFILE=debug ./build-android.sh`, left behind by
 * emulator testing. `build-android.sh` copies whatever cargo last produced;
 * Gradle packaged it without looking; nothing in the tree knew the difference,
 * and Play's size warning was the first signal anything was wrong.
 *
 * [BuildInfo] is generated by the same `build-android.sh` run that installs the
 * `.so` beside it, so its `PROFILE` is a truthful label for that binary — the
 * two are a matched pair and cannot drift within a run. That makes it a better
 * thing to gate on than file size or ELF contents: exact, legible, and it fails
 * in about a second rather than after a full bundle.
 *
 * Debug iteration is untouched — only the release component registers this.
 * There is deliberately no `-P` escape hatch: the whole value is that it cannot
 * be skipped in a hurry, and an escape hatch is how it would be.
 */
val verifyReleaseNativeProfile by tasks.registering {
    group = "verification"
    description = "Fail a release build whose jniLibs came from PROFILE=debug."

    // Resolved at configuration time so the action captures no project state.
    val buildInfo = layout.projectDirectory
        .file("src/main/kotlin/com/beanbeaver/bbreceiptkit/BuildInfo.kt").asFile

    doLast {
        if (!buildInfo.isFile) {
            throw GradleException(
                "bbreceiptkit has no generated BuildInfo.kt — run ./build-android.sh first.",
            )
        }
        val text = buildInfo.readText()
        fun constant(name: String): String? =
            Regex("""$name:\s*String\s*=\s*"([^"]*)"""").find(text)?.groupValues?.get(1)

        val profile = constant("PROFILE")
            ?: throw GradleException("No PROFILE constant in ${buildInfo.path}")
        val abis = constant("ABIS").orEmpty()

        if (profile != "release") {
            throw GradleException(
                """
                |Refusing to build a release against PROFILE=$profile native libraries.
                |
                |bbreceiptkit/src/main/jniLibs/ currently holds the output of
                |    PROFILE=$profile ./build-android.sh
                |
                |A debug libbb_receipt_ffi.so is ~224 MB rather than ~37 MB, and every
                |Rust stage of a scan runs an order of magnitude slower. Shipping one
                |is what earned the Play warning "This artifact significantly increases
                |the size of APK(s) downloaded by users".
                |
                |Fix:  ./build-android.sh          # PROFILE defaults to release
                """.trimMargin(),
            )
        }
        if (!abis.split(' ', ',').map(String::trim).contains("arm64-v8a")) {
            throw GradleException(
                "jniLibs were built for ABIS=\"$abis\", but the app packages arm64-v8a only.",
            )
        }
    }
}

androidComponents {
    onVariants(selector().withBuildType("release")) { variant ->
        // registerPreBuild is the supported Variant-API hook. Don't reach for
        // tasks.named("preReleaseBuild") instead: AGP registers variant tasks in
        // afterEvaluate, i.e. after this script body has already run.
        variant.lifecycleTasks.registerPreBuild(verifyReleaseNativeProfile)
    }
}
